### ISSUE TITLE
Questions about Code

### ISSUE THREAD

**Issue by xhy963319431** [yehjin-shin/BSARec#4]
1.Rename variable 'beta' to 'sqrt_beta' , and it will cause the pre-trained model to run incorrectly.For example, BSARec_Beauty_best.pt . Because this model was trained using 'beta'.
2.In the class FEARecBlock in the _module.py file, it should be self.layer = FEARecLayer(args, layer_num). Your code defaults to layer_num=0

**Comment by yehjin-shin** [comment]
I apologize for the late response, and thank you for pointing out the bugs. I’ve updated the checkpoint file, including the ‘beta’ to ‘sqrt_beta’ renaming, and corrected the FEARec code to properly handle layer_num in FEARecBlock.
