### ISSUE TITLE
How do I get the 0layer_0iter.npy-16layer_4iter.npy of the model in the visualize folder?

### ISSUE THREAD

**Issue by zf-shao** [yehjin-shin/BSARec#5]
The sequence_output folder only gives the visualization of the LastFM dataset. How can I get the npy data of layers 1-16 of other datasets?

**Comment by yehjin-shin** [comment]
You can obtain the .npy data for layers 1-16 of other datasets by adjusting a few settings in the code:

1. **Train a Model with 16 Layers**: Ensure you have a trained model with 16 layers to access the required outputs.
2. **Enable All Layer Outputs**: In the `forward` function of the transformer-based model, set `all_sequence_output=True` to obtain the output sequences for all layers.
3. **Save .npy Files**: After setting `all_sequence_output=True`, you’ll get the sequence outputs of all layers. Simply save them as .npy files to use for visualization.

Let me know if you have any other questions.
