### ISSUE TITLE
Question About Data Figures and Frequency Amplitude Calculation in Transformer-Based Model

### ISSUE THREAD

**Issue by lulusiyuyu** [yehjin-shin/BSARec#6]
Hi, I’ve been going through your paper and have a question about the data figures, especially those related to the transformer-based model. How did you calculate the amplitude for the different frequencies?

I’ve read the original FMLP-Rec paper and understand how the FMLP-Rec curve is generated, but I’m a bit unclear about the other curves in your paper. Could you explain how you got them?

Thanks a lot for your help! Looking forward to your response.

Figure 1: Data figure from your paper related to the transformer-based model
![image](https://github.com/user-attachments/assets/e89813d2-2b20-404b-8181-41d3e816e668)

Figure 2: Data figure from the FMLP-Rec paper, illustrating the process of generating the FMLP-Rec curve.
![image](https://github.com/user-attachments/assets/3b3365e5-4f11-4e53-8830-08cdf1a0b2bf)

**Comment by yehjin-shin** [comment]
Hi, thank you for your interest in our work. **I recently updated the visualization code, which may address your questions.** 

Regarding the differences between our implementation and FMLP's implementation, I would like to clarify the calculation of the y-axis. Both implementations rely on the weights of the filter layer, but there is a difference in how the amplitude is calculated. While we compute the amplitude as $a^2 + b^2$, where the complex number is represented as $a + bi$, I wonder if FMLPRec might use only the real part of the complex number. This is just a guess based on the fact that their y-values include negative numbers, which would not be possible if they calculated the amplitude as $a^2 + b^2$.

I hope this clarifies your concerns. If this interpretation is incorrect, I would be happy to discuss it further or hear your explanation. Please let me know if you have any feedback!

**Comment by lulusiyuyu** [comment]
Thank you so much for your help! I really appreciate the time you took to assist me. I apologize for not noticing the visualization code in your repository—it actually answered my question. Sorry for any inconvenience I may have caused. Your work is truly impressive, and I’m grateful for your contribution!
